Libreria# Generación de Datos de Prueba

En este notebook se generan:

- 5,000 clientes
- 500 productos
- 100,000 ventas

Posteriormente se exportan a formato CSV para ser cargados en BigQuery.

In [3]:
import pandas as pd
import random
from faker import Faker as Faker
from datetime import datetime, timedelta

fake = Faker()

random.seed(42)
Faker.seed(42)

Generar clientes:

In [4]:
clientes = []

paises = [
    "Guatemala",
    "El Salvador",
    "Honduras",
    "Costa Rica"
]

for i in range(1, 5001):
    clientes.append({
        "id_cliente": i,
        "nombre": fake.name(),
        "pais": random.choice(paises)
    })

clientes_df = pd.DataFrame(clientes)

clientes_df.head()

   id_cliente           nombre         pais
0           1     Allison Hill    Guatemala
1           2      Noah Rhodes    Guatemala
2           3  Angie Henderson     Honduras
3           4    Daniel Wagner  El Salvador
4           5  Cristian Santos  El Salvador

Generar producto

In [5]:
categorias = [
    "Electrónica",
    "Hogar",
    "Ropa",
    "Deportes",
    "Alimentos"
]

productos = []

for i in range(1, 501):
    productos.append({
        "id_producto": i,
        "producto": f"Producto_{i}",
        "categoria": random.choice(categorias)
    })

productos_df = pd.DataFrame(productos)

productos_df.head()

   id_producto    producto    categoria
0            1  Producto_1        Hogar
1            2  Producto_2         Ropa
2            3  Producto_3  Electrónica
3            4  Producto_4         Ropa
4            5  Producto_5     Deportes

Generar Ventas

In [6]:
ventas = []

sucursales = [
    "San Salvador",
    "Guatemala City",
    "Tegucigalpa",
    "San José"
]

fecha_inicio = datetime(2025, 1, 1)

for i in range(1, 100001):

    fecha = fecha_inicio + timedelta(
        days=random.randint(0, 365)
    )

    ventas.append({
        "id_venta": i,
        "fecha_venta": fecha.date(),
        "id_cliente": random.randint(1, 5000),
        "id_producto": random.randint(1, 500),
        "sucursal": random.choice(sucursales),
        "monto": round(random.uniform(10, 500), 2)
    })

ventas_df = pd.DataFrame(ventas)

ventas_df.head()

   id_venta fecha_venta  id_cliente  id_producto        sucursal   monto
0         1  2025-03-24         607          142    San Salvador  197.57
1         2  2025-06-20         493          133     Tegucigalpa   97.19
2         3  2025-02-05        4029          476  Guatemala City  309.05
3         4  2025-04-02        4031           56  Guatemala City  274.91
4         5  2025-08-09        1790          315    San Salvador  457.18

GUARDAR CSV

In [8]:
clientes_df.to_csv("../datasets/clientes.csv", index=False)

productos_df.to_csv("../datasets/productos.csv", index=False)

ventas_df.to_csv("../datasets/ventas.csv", index=False)

print("Archivos CSV generados correctamente")

Archivos CSV generados correctamente

VERIFICACIÓN

In [7]:
print("Clientes:", len(clientes_df))
print("Productos:", len(productos_df))
print("Ventas:", len(ventas_df))

Clientes: 5000
Productos: 500
Ventas: 100000